---
name: WindHA
version: dev
slug: windha
description: display wind mobi add-on by Community Home Assistant Add-ons
url: https://github.com/hassio-addons/addon-windha
codenotary: codenotary@frenck.dev
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
